name: Run tests
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_macOS_xcode_16:
    name: Build and Test on macOS with Xcode 16
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Show current version of Xcode
        run: xcodebuild -version
      - name: Test
        run: |
          make ci
          set -o pipefail && xcodebuild test -scheme "Cuckoo-macOS" -workspace Cuckoo.xcworkspace \
            | tee test.log | xcbeautify --renderer github-actions
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-xcode16
          path: test.log

  test_macOS_xcode_15:
    name: Build and Test on macOS with Xcode 15
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Show current version of Xcode
        run: xcodebuild -version
      - name: Test
        run: |
          make ci
          set -o pipefail && xcodebuild test -scheme "Cuckoo-macOS" -workspace Cuckoo.xcworkspace \
            | tee test.log | xcbeautify --renderer github-actions
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-xcode15
          path: test.log

  test_iOS:
    name: Build and Test on iOS simulator
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Show current version of Xcode
        run: xcodebuild -version
      - name: Test
        run: |
          make ci
          set -o pipefail && xcodebuild test -scheme "Cuckoo-iOS" -workspace Cuckoo.xcworkspace \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.0" \
            | tee test.log | xcbeautify --renderer github-actions
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-ios
          path: test.log
